### ISSUE TITLE
Require statements with .c files compilation problem

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/chapel#12844]
### Summary of Problem
Require statements with .c files only work when the .c file being required lives in the same directory as the compilation command is being executed from.  When the .c file lives in a different directory (even one specified via `-M`, or the same directory as the .chpl file that relies on it), the Chapel compiler cannot find it.

### Steps to Reproduce

**Source Code:**

requireInDiffDir.chpl:
```chapel
use helperMod;

writeln(callBar());
```

subDir/helperMod.chpl:
```chapel
require "foo.c", "foo.h";

extern proc bar(): c_int;

proc callBar(): c_int {
  return bar();
}
```

subDir/foo.h:
```C
int bar(void);
```

subDir/foo.c:
```C
#include "foo.h"

int bar() {
  return 2;
}
```

**Compile command:**
`chpl requireInDiffDir.chpl -M subDir`

**Associated Future Test(s):**
[`test/visibility/require/requireInDiffDir.chpl`](https://github.com/chapel-lang/chapel/blob/master/test/visibility/require/requireInDiffDir.chpl) #12845

### Configuration Information

- Output of `chpl --version`: 1.20.0 pre-release

**Comment by lydia-duncan** [comment]
I discovered this when playing around with ZMQ and multilocale libraries:

The helper function I defined in a .h file were turning up as duplicate symbols when I tried to compile a C program using the generated library file, so I tried to move the definitions into a .c file, but the compiler couldn't find the .c file unless it was in the directory where I was compiling the .chpl code into a library.

**Comment by bradcray** [comment]
Does it work if you `require "subDir/foo.c", "subDir/foo.h";`?

**Comment by lydia-duncan** [comment]
Yes, but then helperMod.chpl doesn't compile on its own (and also refers to a directory structure that does not reflect its current location)

**Comment by lydia-duncan** [comment]
I think ideally we should check for required .c files relative to the location of the file that relies on them.

**Comment by bradcray** [comment]
I think I buy that argument...

**Comment by bradcray** [comment]
I've got an attempt at fixing this here:  https://github.com/bradcray/chapel/tree/search-reqs-in-local-dirs
(running testing now)

**Comment by bradcray** [comment]
Testing seems to be coming in clean.

**Comment by lydia-duncan** [comment]
Would you like me to review the open PR?

**Comment by bradcray** [comment]
Let's solicit comments on the proposal first.  I'll send out a mail.

**Comment by vasslitvinov** [comment]
This looks like a no-brainer to me, too.
