### ISSUE TITLE
should we stop bundling fltk?

### ISSUE THREAD

**Issue by mppf** [chapel-lang/chapel#26370]
We have a bundled fltk in third-party/fltk for use by chplvis. However, this bundled fltk does not currently build for me on Mac OS X 14.6 (with homebrew) or on Ubuntu 24.04. I see different errors on each.

<details>

Mac OS X error

```
In file included from png.c:14:
./pngpriv.h:920:4: error: ZLIB_VERNUM != PNG_ZLIB_VERNUM       "-I (include path) error: see the notes in pngpriv.h"
  920 | #  error ZLIB_VERNUM != PNG_ZLIB_VERNUM \
      |    ^
Compiling arm/filter_neon_intrinsics.c...
```

Ubuntu error

```
Package xft was not found in the pkg-config search path.
Perhaps you should add the directory containing `xft.pc'
to the PKG_CONFIG_PATH environment variable
Package 'xft', required by 'virtual:world', not found
Package freetype2 was not found in the pkg-config search path.
Perhaps you should add the directory containing `freetype2.pc'
to the PKG_CONFIG_PATH environment variable
Package 'freetype2', required by 'virtual:world', not found
checking for freetype-config... no
configure: please install pkg-config or use 'configure --disable-xft'.
configure: error: Aborting.
```

This error is strange on ubuntu as I've installed fltk, so you would think that the dependencies are available. Yes I could be missing some development packages, but even so.

</details>

I am thinking that our users will have a better experience if we ask them to install `fltk` somehow if they want to use `chplvis` (rather than us trying to support building it on the variety of configurations and systems). Note that `fltk` is available in Ubuntu, Homebrew, and Spack. As far as I know, `chplvis` works with `fltk` 1.3.9 and 1.4.0 which are the versions that I see available in these package managers.

Even if there weren't challenges to building fltk on different systems, there is still an advantage to asking users to install it with a package manager. That's because fltk itself has a number of dependencies. If we have to ask users to install something, why not ask them to install fltk itself?

**Comment by bradcray** [comment]
My initial reaction to this was along the lines of "sure, but why not provide both `CHPL_FLTK=system|bundled` options and just do a better job of keeping our bundled version up-to-date?"  But this part resonated with me:

> fltk itself has a number of dependencies. If we have to ask users to install something, why not ask them to install fltk itself?

The build errors you encountered also make me wonder whether we should add `chplvis` to our platform portability testing to head off such issues in the future…  But that gets a little bit into the "Is the effort worth the benefit?" question (where maybe the answer depends somewhat on how much value you got out of chplvis for your use of it today?)

**Comment by damianmoz** [comment]
Whoever in the first place choose FLTK as an underlying toolkit made a very wise choice. My 2c,

**Comment by mppf** [comment]
@bradcray - it sounds like you are OK with removing the bundled version for now. Am I understanding correctly?

Regarding

> "sure, but why not provide both CHPL_FLTK=system|bundled options and just do a better job of keeping our bundled version up-to-date?"

It's not necessarily the case that updating the bundled fltk would resolve the issue. The problem with building it on Mac OS X has to do with some hacky-looking checks on include paths that the libpng header files are doing, so whether or not it works can depend on what `-I` options are provided.

I took a quick look at upgrading the bundled version and I'm seeing issues where it doesn't find the Homebrew install of libpng. We could try to modify it to do that, but I still think the simpler path is for chplvis to depend on an already-installed fltk.

> But that gets a little bit into the "Is the effort worth the benefit?" question (where maybe the answer depends somewhat on how much value you got out of chplvis for your use of it today?)

Well, I got as far as getting chplvis to build, noticing it was core-dumping, and fixing the core dump before I decided to look at the verbose CommDiagnostics log instead. Basically, I ran into too many roadblocks with chplvis and gave up before it had a chance to help me understand my actual problem. I'm trying to fix the roadblocks, but I haven't gained information about its utility.

**Comment by bradcray** [comment]
> it sounds like you are OK with removing the bundled version for now. Am I understanding correctly?

Yes, I think I would be.  Just as a reminder, what are the other things fltk requires that we don't bundle that you alluded to above?

> Well, I got as far as getting chplvis to build, noticing it was core-dumping, and fixing the core dump before I decided to look at the verbose CommDiagnostics log instead

:'(
