### PR TITLE
Bug fixes for --llvm-wide-opt and multilocale unwind

### PR DESCRIPTION
**Pull request by mppf**
This PR is a group of bug fixes. The main bug fixes are:

* fixes a bug causing --llvm-wide-opt not to make it through code generation (needed to update for file name -> file number change from PR #3049)
* fixes PRIM_CHPL_COMM_ARRAY_GET to work properly with --llvm-wide-opt. It was running a *PUT* in that configuration because the --llvm-wide-opt section wasn't properly updated when PRIM_CHPL_COMM_ARRAY_GET was introduced in PR #2927.

I also made other bug fixes in the process of debugging the main problems:

* adjusts error.c to allow CHPL_UNWIND=libunwind to work in multilocale builds. Before this change, that would result in compilation errors when building error.c for the launcher.
* fixes PRIM_WIDE_GET_ADDR so that it works with --llvm
* fixes a code generation failure with the C backend and CHPL_WIDE_POINTERS=node16

TODO:
* Enable basic nightly testing for --llvm-wide-opt
* Other LLVM todos:
  * Fix --llvm-wide-opt to work with CHPL_WIDE_POINTERS=struct and deprecate CHPL_WIDE_POINTERS=node16.
  * Associate Chapel AST ids with LLVM IR for debugging
  * Turn on the generation of LLVM TBAA metadata nodes
  * Investigate struct-path-aware TBAA
  * add loop vectorization hints
  * indicated when a load is from const data
  * experiment with the Polly optimizer
  * check that Chapel's LLVM IR generation meets LLVM best practices

Testing:
* passed quickstart with CHPL_UNWIND=libunwind in test/runtime/panzone
* passed quickstart+GASNet with CHPL_UNWIND=libunwind in test/runtime/panzone
* passed quickstart testing
* hello.chpl works with --llvm --llvm-wide-opt --fast with GASNet and WIDE_POINTERS=node16
* passed full local testing

Reviewed by @vasslitvinov - thanks!

### CODE REVIEW

**Comment by vasslitvinov** [comment]
Looks good to me.
