### PR TITLE
Domain stabilization items

### PR DESCRIPTION
**Pull request by vasslitvinov**
Domain stabilization items

This PR implements several minor action items from Domain module review and adds tests.

* Clear compiler errors for operators `#`, `by`, `align` when they are invoked incorrectly.
  Move array overloads for `#` from ChapelDomain.chpl to ChapelArray.chpl. Errors for those overloads are now reported by the domain `#`.
  Add some error overloads.

* Make it a compiler error to invoke `==` or `!=` on domains of a different kind, ex. on a rectangular domain and an irregular domain.
  Introduce the function `chpl_sameDomainKind` to guard such comparisons when desired. It is now used in one case in ChapelAutoLocalAccess.chpl where it is OK that two domains compare as not equal when they are of a different kind.

* Add missing implementations of `dsiTargetLocales()` to DefaultDist, DefaultAssociative and DefaultSparse. dsiTargetLocales was introduced in 0289958038 with these cases left unimplemented.

### While there:

* Add pragma "last resort" on some error overloads.

* Remove some where-clauses to facilitate error reporting and reduce the amount of work for resolution.

* Reorder some existing error overloads to match the order of those methods established in #19307.

* Remove two `return r;` that follow compilerError() as unreachable. This resulted in additional compilation errors in four tests that are compiled with --ignore-errors-for-pass. I updated their .good files.

* Issue "unstable" warnings in `bulkAdd` and `makeIndexBuffer` and update the documentation for the former to indicate that it is unstable. The latter already had that verbage.

### Discussion - promotability of #, by, align

This implements the suggestion in https://github.com/chapel-lang/chapel/issues/19348#issuecomment-1058737329 . The operators `#` `by` `align` are now promotable over the first operand. W.r.t. the second operand:

* operators `align` on range and `#` are promotable because their "normal" overloads accept the second argument only of a certain type, roughly:
```chpl
operator #(r:range(?i), count:chpl__rangeStrideType(i)) // return a new range
/*last resort*/ operator #(r: range(?i), count)         // error "incorrect count type"
/*last resort*/ operator #(r, count)                    // error "# not supported on r.type"
```

* operators `align` on domain and `by` are not promotable because their "normal" overloads have an unrestricted-generic second argument, with error checking done internally:
```chpl
operator by(r : range(?), step)      // return a new range or report an error
/*last resort*/ operator by(r, step) // error "'by' is not supported on r.type"
```

In the current implementation, the presence of a blanket last-resort overload prevents the possibility of forwarding the operators. I propose that we change the behavior so that forwarding takes precedence over last-resort.

### Discussion - error overloads for dsiTargetLocales() et al.

I did not add last-resort error overloads for dsiTargetLocales() in the style of #19070. Because otherwise I'd have to add the `overload` annotation to a bunch of existing implementations of dsiTargetLocales for all our domain maps. This seemed like an overkill.

Should we add missing last-resort error overloads for the other methods systematized in #19307? Seems like a good idea, however might be an overkill especially for methods like dsiDims() and dsiNumIndices() that, really, every domain map should implement.

### Other potential next steps

* Remove `inline` on some implementations of domain `==` that contain for-loops.
* Turn `chpl_sameDomainKind()` into a user-facing function. Perhaps rename it to something like `isEqualityComparisonAvailable()`.

Testing:
* [ ] standard paratest
* [ ] gasnet paratest over multilocale tests

### CODE REVIEW

**Review by stonea — COMMENTED** [review]
Edit: Looks like I accidentally added this as a comment rather than a review item. I was asking about the use of `pragma "fn returns aliasing array"`

Just out of curiosity what is the purpose of this pragma? I get the returned array is kind of a slice\view into `arr` but why do we need to mark the function with this?

File: modules/internal/ChapelDomain.chpl [hunk 1]
```diff
@@ -462,14 +460,35 @@ module ChapelDomain {
...
+    if d1.isRectangular() then
+      compilerError("comparing a rectangular domain against",
+        " an associative or sparse domain is not currently supported");
+    if d1.isAssociative() then
+      compilerError("comparing an associative domain against",
+        " a rectangular or sparse domain is not currently supported");
+    if d1.isSparse() then
+      compilerError("comparing a sparse domain against",
+        " a rectangular or associative domain is not currently supported");
+    // we should not get here, however if we do...
```
Comment (stonea) [inline modules/internal/ChapelDomain.chpl:473]: Why not make this an assertion instead so it becomes evident that we have a bug in our module code?

File: modules/internal/ChapelDomain.chpl [hunk 2]
```diff
@@ -462,14 +460,35 @@ module ChapelDomain {
...
+    cmpError(d1, d2);
+  }
+
+  inline operator !=(d1: domain, d2: domain) {
+    cmpError(d1, d2);
   }
 
+  // check this before comparing two domains with == or !=
+  proc chpl_sameDomainKind(d1: domain, d2: domain) param
+    return (d1.isRectangular() && d2.isRectangular()) ||
```
Comment (stonea) [inline modules/internal/ChapelDomain.chpl:488]: Is there no better way to do this than exhaustively comparing each of the domain types? We can't do something like: `d1.domainKind == d2.domainKind`

If we add a new domain type or change rectangular to mean (dense rectangular or sparse) we'd have to remember to update this code.

File: modules/internal/ChapelDomain.chpl [hunk 3]
```diff
@@ -707,6 +726,8 @@ module ChapelDomain {
 
   // This is the definition of the 'by' operator for domains.
   operator by(a: domain, b) {
+    if ! a.isRectangular() then compilerError(
+      "cannot apply 'by' to associative and sparse domains");
```
Comment (stonea) [inline modules/internal/ChapelDomain.chpl:730]: On the one hand I'd be tempted to make error messages like this say "non rectangular" just on the off chance we end up adding some new domain type later.

On the other hand users may find it clearer if we list it out explicitly and I guess its unlikely to change.

I suppose we could solve this by making the if statement match the error message and adding an assert to catch any unexpected new domain kind:

```
if(a.Sparse() || a.isAssociative) then compilerError(/*what you have now*/)
assert(a.isRectangular());
```

File: modules/internal/ChapelDomain.chpl [hunk 4]
```diff
@@ -720,6 +741,8 @@ module ChapelDomain {
   // It produces a new domain with the specified alignment.
   // See also: 'align' operator on ranges.
   operator align(a: domain, b) {
+    if ! a.isRectangular() then compilerError(
```
Comment (stonea) [inline modules/internal/ChapelDomain.chpl:744]: Same sort of comment as the previous one here.

**Comment by vasslitvinov** [comment]
@stonea I believe pragma `fn returns aliasing array` means that the array it returns does not have its own elements, instead it points into somebody else's elements. Not sure if it is used for lifetime checking or determine when to delete the elements or something else.

File: modules/internal/ChapelDomain.chpl [hunk 5]
```diff
@@ -1768,13 +1793,16 @@ module ChapelDomain {
...
-          The interface and implementation is not stable and may change in the
+          The interface and implementation are not stable and may change in the
           future.
 
      :arg size: Size of the buffer in number of indices.
      :type size: int
     */
     inline proc makeIndexBuffer(size: int) {
+      if chpl_warnUnstable then compilerWarning(
+        "makeIndexBuffer() is subject to change in the future.");
```
Comment (stonea) [inline modules/internal/ChapelDomain.chpl:1804]: It's not something that's in the scope of this review but I kind of wish we had an `unstable` keyword kind of like we do for `deprecated`. It's kind of annoying that we have to manually write this if statement and warning in every place.

Pinging @lydia-duncan since I think you did the work to add the `deprecated` keyword (no good deed goes unpunished :-)). Have we thought of this before, do you have a sense of if it would be difficult to add?

At a minimum it would be nice if we just had some kind of utility function
warnUnstable(fcnName : string) that did the check and made the error for us.

**Review by stonea — COMMENTED** [review]
Need to step out now, so I'll post my review so far. I'll come back to it later today.

File: modules/internal/ChapelDomain.chpl (hunk 1 above)
Comment (vasslitvinov) [reply modules/internal/ChapelDomain.chpl:473]: The `==` and `!=` operators are available to the public, so the error case is not necessarily our bug. Really, it may not be a bug at all. Hence a user-friendly error message.

File: modules/internal/ChapelDomain.chpl (hunk 2 above)
Comment (vasslitvinov) [reply modules/internal/ChapelDomain.chpl:488]: Not that I know. I agree this implementation is not ideal. Also, it is tied to the current implementation of `==`. For example, if `==` allowed us to compare sparse against associative, this would return true for any combination of irregular domains. Maybe it should really be called "equalityIsImplemented". I updated the OP for this.

File: modules/internal/ChapelDomain.chpl (hunk 3 above)
Comment (vasslitvinov) [reply modules/internal/ChapelDomain.chpl]: Implemented, and the other ones, too.

File: modules/internal/ChapelDomain.chpl [hunk 6]
```diff
@@ -462,14 +466,35 @@ module ChapelDomain {
...
+        " a rectangular or associative domain is not currently supported");
+    // we should not get here, however if we do...
+    compilerError("comparing '", d1.type:string, "' against '",
+                  d2.type:string, "' is not currently supported");
   }
 
-  inline operator !=(d1: domain, d2: domain) param {
-    return true;
+  inline operator ==(d1: domain, d2: domain) {
+    cmpError(d1, d2);
```
Comment (stonea) [inline modules/internal/ChapelDomain.chpl:485]: Maybe I'm missing something, but don't we only want to call out to cmpError if d1 and d2 aren't the same kind?

**Review by stonea — APPROVED** [review]

File: modules/internal/ChapelDomain.chpl (hunk 6 above)
Comment (vasslitvinov) [reply modules/internal/ChapelDomain.chpl:485]: Right. However, if d1 and d2 are of the same kind, then another overload gets selected by resolution.
