### ISSUE TITLE
Chpl 1.20 + gcc 8.3.0 -- compilation error

### ISSUE THREAD

**Issue by carcarah** [chapel-lang/chapel#14950]
### Summary of Problem

Hello everyone.

I'm facing problems when trying to compile a chpl program with chpl 1.20 and gcc 8.3.0.

**Compile command:**

`chpl -M modules --permit-unhandled-module-errors --fast --scalar-replacement implementation/fsp_gen.c implementation/simple_bound.c implementation/aux.c implementation/tsp.c main.chpl -o ga.out`

I.e., I'm using C-interoperability. But, even trying to compile `hello6-taskpar-dist` results in errors. 

Here is the is the [output](https://textuploader.com/16gk8).

### Script I use for configuration:

`#!/bin/bash`

`export CHPL_HOME=~/chapel-1.20.0`
`export CHPL_HOST_PLATFORM=`$CHPL_HOME/util/chplenv/chpl_platform.py``
`export PATH="$PATH":"$CHPL_HOME/bin/$CHPL_HOST_PLATFORM"`
`export MANPATH="$MANPATH":"$CHPL_HOME"/man`
`NUM_T_LOCALE=$(cat /proc/cpuinfo | grep processor | wc -l)`
`export CHPL_RT_NUM_THREADS_PER_LOCALE=$NUM_T_LOCALE`
`export CHPL_TARGET_CPU='native'`
`export CHPL_TASKS=qthreads`
`cd $CHPL_HOME`
`make`

### An interesting fact is that

-- If I unload gcc 8.4, then  `module load gcc/7.4.0_gcc-6.4.0`,` make clean` on chpl home, my code compiles.

-- Chapel 1.19 works fine with gcc 8.3.0,  I don't need to unload gcc 8.3.0.

**Comment by carcarah** [comment]
Hello everyone. Please let me know if you need my code for testing. Tiago Carneiro.

**Comment by mppf** [comment]
@carcarah - can you tell us the OS version? Sometimes you can get this in `cat /etc/issue` and sometimes you can use `lsb_release -a`. Thanks.

**Comment by carcarah** [comment]
Sure. `cat /etc/issue` --> Debian GNU/Linux 10 \n \l
and
`lsb_release -a` --> 

Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

**Comment by dlongnecke-cray** [comment]
Hi @carcarah, can you give me the output of `printchplenv --all`?

**Comment by carcarah** [comment]
Hello @dlongnecke-cray , here is the output.

CHPL_HOST_PLATFORM: linux64 *
CHPL_HOST_COMPILER: gnu
CHPL_HOST_ARCH: x86_64
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native *
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads *
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: gmp
CHPL_HWLOC: hwloc
CHPL_REGEXP: re2
CHPL_LLVM: llvm
CHPL_AUX_FILESYS: none
CHPL_LIB_PIC: none

**Comment by dlongnecke-cray** [comment]
Hi @carcarah, with `gcc/8.3.0` and `chpl-1.20` loaded, can you go ahead and run your setup script, and then, from $CHPL_HOME:

```
make clobber
make
```

We want to rebuild the libraries Chapel uses in `$CHPL_HOME/third-party` so that they are built with `gcc/8.3.0`. 

It looks like you have `CHPL_LLVM=llvm`, so this might take awhile. For what it's worth, I don't think that you need to have LLVM to test if the fix works, so if you want to speed things up you could try `CHPL_LLVM=none` before you rebuild.

**Comment by carcarah** [comment]
Hello @dlongnecke-cray ,

now it works. Thanks!

I've got a question: when should I `make clobber` and `make`? The first time I build the runtime?

**Comment by bradcray** [comment]
Building for the first time from a clean copy of the release should never require `make clobber`.

I would say that, in general (and if things are working correctly), `make clobber` should not be required unless you have an existing build; then your system switches versions of tools, compilers, OS, etc.; then you try to compile using your existing build or to rebuild it in place such that only some things are rebuilt.

That said, there are some rare cases where if you have an existing copy of the Chapel source tree, then update it to a newer copy and try to rebuild in place, make clobber can be required (this shouldn't affect those working from official releases if they give them each their own directory; only those who are pulling from master with some regularity).

(I'll be curious if others on the team disagree with any of the above)

**Comment by dlongnecke-cray** [comment]
Glad to see everything is working, @carcarah! Happy compiling with 1.20.

You shouldn't ever really need to `make clobber` as an end user (though Brad does illustrate a good example), but upgrading your C compiler while using libraries built by an old version is an exception.

In this case, the bug is due to your `gcc/8.3.0` being configured to build position independent executables (PIEs) by default, while your old version is not configured to do so.

SInce your issue seems to be resolved, let me know if it's OK to close this thread.

**Comment by carcarah** [comment]
Hello @dlongnecke-cray and @bradcray . I think the compilers from Grid'5000 were updated and I didn't notice it.

I checked here, and I'm able to compile all my distributed and single-locale codes.

Thank you!

**Comment by dlongnecke-cray** [comment]
Sounds good. Happy coding!
