### PR TITLE
Avoid boolean `&` warning in `testRecursionFails`

### PR DESCRIPTION
**Pull request by riftEmber**
Cast boolean operands to `&` in `testRecursionFails` to ints, to avoid warnings with some compilers.

Compiling `testRecursionFails` fails on my system since https://github.com/chapel-lang/chapel/pull/24321 with this error:
```
/Users/rift/chapel/frontend/test/framework/testRecursionFails.cpp:166:11: error: use of bitwise '&' with boolean operands [-Werror,-Wbitwise-instead-of-logical]
    res = queryF(context, callFFirst, runHandler) &
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                  &&
/Users/rift/chapel/frontend/test/framework/testRecursionFails.cpp:166:11: note: cast one or both operands to int to silence this warning
```

I see this didn't come up in CI checks on that PR and assume it is compiler version specific. Casting to int should avoid the error for compilers that care about it without breaking anything. Switching to logical `&&` isn't an option as it short-circuits and we don't want that.

[reviewer info placeholder]

Testing:
- [x] dyno tests in CI
- [x] dyno tests on my local

### CODE REVIEW

**Comment by DanilaFe** [comment]
What a silly warning -- what if I don't want short-circuiting?

**Review by DanilaFe — APPROVED** [review]
