### PR TITLE
Update spack version for mason --external

### PR DESCRIPTION
**Pull request by mppf**
When running `mason external --setup` on Ubuntu 22.10 or SLES 15, I was seeing an error from Spack itself. That is because we had pinned version v0.15.4 in the mason source code and this version does not work with Python 3.10 (only Python 3.5 - 3.8).

The error included this from within Spack code:

    AttributeError: module 'collections' has no attribute 'MutableMapping'

Once I updated the version number to the current Spack release (v0.19.0), `mason external --setup` still did not work, because of differences in how `spack --version` output changed. So, I updated the trimming used when processing the output of `spack --version`.

- [ ] wait for https://github.com/spack/spack/issues/22548 to be resolved; or some other solution (say, using `/tmp` for the spack installs in our testing)

### CODE REVIEW

**Comment by ronawho** [comment]
This is https://github.com/Cray/chapel-private/issues/3518 / https://github.com/Cray/chapel-private/issues/3206. Don't think we can just upgrade without introducing some other problems.

I suppressed mason-external failures for m1 in https://github.com/chapel-lang/chapel/pull/20118, but seems like we should update those suppress-ifs to check python version (and then try to get somebody on upgrading spack versions so we're not just missing spack testing on chapdl)

**Comment by bmcdonald3** [comment]
Additionally, see https://github.com/chapel-lang/chapel/issues/19517#issuecomment-1211006412.

I similarly don't think we can just upgrade this.

**Comment by mppf** [comment]
😱

**Comment by ronawho** [comment]
> wait for https://github.com/spack/spack/issues/22548 to be resolved; or some other solution (say, using /tmp for the spack installs in our testing)

https://github.com/chapel-lang/chapel/pull/21473 uses `/tmp` for spack installs in testing
