### ISSUE TITLE
Internal compiler error for `c_FILE` type mismatch

### ISSUE THREAD

**Issue by jeremiah-corrado** [chapel-lang/chapel#22492]
## Summary of Problem

Consider the following program:

```chapel
use CTypes;

extern proc fopen(filename: c_string, mode: c_string): c_FILE;
extern proc fclose(file: c_FILE): c_int;

var f = fopen(c"test.txt", c"w");
flose(f);
```

With the changes introduced in https://github.com/chapel-lang/chapel/pull/22435, the extern declarations should now be written as follows because a `c_FILE` no longer includes the pointer:
```chapel
extern proc fopen(filename: c_string, mode: c_string): c_ptr(c_FILE);
extern proc fclose(file: c_ptr(c_FILE)): c_int;
```
However, compiling the erroneous program with the `-scFileTypeHasPointer=false` flag set to adopt the new behavior, I'm seeing the following errors:

1. With `CHPL_TARGET_COMPILER=llvm`:
```
Assertion failed: (from.val), function codegenAssign, file cg-expr.cpp, line 3749.
```

2. With `CHPL_TARGET_COMPILER=clang`:
```
error: assigning to '_cfiletype' (aka 'struct __sFILE') from incompatible type 'FILE *' (aka 'struct __sFILE *'); dereference with *
call_tmp_chpl37 = fopen("test.txt", "w");
                ^ ~~~~~~~~~~~~~~~~~~~~~~
                  *
file_bug.c:16:8: error: passing '_cfiletype' (aka 'struct __sFILE') to parameter of incompatible type 'FILE *' (aka 'struct __sFILE *'); take the address with &
fclose(f_chpl);
       ^~~~~~
       &
path/to/include/stdio.h:143:19: note: passing argument to parameter here
int      fclose(FILE *);
                      ^
2 errors generated.
```

## Discussion

For the LLVM backend, the user is given no indication of what went wrong. Given that users who are adopting their code from the old `c_FILE` behavior to the new behavior are pretty likely to run into this, I think it needs to be corrected soon. 

With the C backend, the situation is somewhat better, as the C compiler's error message indicates generally what went wrong, only with the incorrect names for formals, types and variables. This error message could be improved and occur earlier in compilation (which would probably also prevent the LLVM failure mode).
